taier-common/src/main/java/com/dtstack/taier/common/constant/CommonConstant.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/service/ComponentConfigService.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/utils/LocalCacheUtil.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/zookeeper/watcher/LocalCacheWatcher.java
change zkService inject way to avoid inject null
=> feat_local_cache_inject_zkService：change zkService inject way

README.md, website/docs/contributing.md
[feat_doc][taiga-all] introduction、Readme
=> [feat_doc][taiga-all] introduction、Readme

README.md, website/docs/quickstart/deploy/pre-operation.md
README.md Document error correction
=> [feat_doc][taier-all] Document error correction

taier-ui/src/pages/console/cluster/newEdit/components/multiVerComp/index.tsx
=> [issue_247][taier-ui]fix can add multiply versions in cluster

taier-ui/src/components/dataSync/index.tsx, taier-ui/src/pages/rightBar/index.tsx, taier-ui/src/pages/workbench.tsx
=> [issue_265][taier_ui] replace the SplitPane component

taier-scheduler/src/main/java/com/dtstack/taier/scheduler/zookeeper/ZkService.java, taier-worker/taier-plugin-api/src/main/java/com/dtstack/taier/pluginapi/enums/TaskStatus.java
It is suggested to change into English notes
=> Use English notes

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/MultiEngineServiceFactory.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchTaskService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/ComponentHiveServerService.java
[feat-taier][taier-data-develop]fix addTask Bug,add hiveServerService
=> [feat-taier][taier-data-develop]fix addTask Bug,add hiveServerService

taier-ui/src/components/dataSync/channel.tsx, taier-ui/src/components/dataSync/index.tsx, taier-ui/src/components/dataSync/interface.ts, taier-ui/src/components/dataSync/source.tsx, taier-ui/src/components/dataSync/target.tsx, taier-ui/src/components/helpDoc/docs.tsx, taier-ui/src/components/task/open.tsx
=> [feat_increment][taier-ui]support increment for dataSync

taier-ui/src/components/helpDoc/docs.tsx, taier-ui/src/components/task/importTemplate.tsx, taier-ui/src/components/task/open.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/extensions/languages/index.tsx, taier-ui/src/interface.ts, taier-ui/src/utils/extensions.tsx
=> [feat_createModal][taier-ui]support to set model for dataSync

taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/pages/dataSource/add.tsx, taier-ui/src/pages/index.tsx
- 移除目录树默认的右键菜单
- 优化删除任务的提示
- 新增关闭页面的弹窗提示
- 移除请求失败的重复提示
=> [fix_ui][taier-ui]fix some details in UI interface

taier-ui/src/components/functionManager/index.tsx, taier-ui/src/components/resourceManager/index.tsx, taier-ui/src/services/functionManagerService.ts, taier-ui/src/services/resourceManagerService.ts
=> [fix_expandKeys][taier-ui]fix can't expand folders

taier-data-develop/src/main/java/com/dtstack/taier/develop/config/MvcConfig.java
fix Backend api responds garbled in browser (#297)
=> fix: Backend api responds garbled in browser (#297)

taier-ui/src/components/dataSync/help.ts, taier-ui/src/extensions/editor/index.tsx
=> [fix_save][taier-ui]fix lost sqlText when saving

taier-ui/src/api/req.ts, taier-ui/src/api/reqOffline.ts, taier-ui/src/extensions/editor/index.tsx
=> [refactor_req][taier-ui]replace the path of offline request

taier-ui/src/components/dataSync/help.ts, taier-ui/src/components/dataSync/interface.ts, taier-ui/src/components/dataSync/source.tsx, taier-ui/src/components/dataSync/target.tsx, taier-ui/src/components/helpDoc/docs.tsx, taier-ui/src/constant/index.ts
=> [feat_dataSync][taier-ui]support ES and HBASE dataSource in dataSync

README.md, website/docs/guides/introduction.md, website/docs/quickstart/rely.md
=> [issue-313][website] modify Flinkx -> Chunjun

taier-ui/src/pages/console/cluster/newEdit/components/multiVerComp/index.tsx, taier-ui/src/pages/console/cluster/newEdit/help.ts, taier-ui/src/pages/console/cluster/newEdit/index.tsx
多集群管理支持对多版本组件的变更进行对比校验
编辑多版本组件内容后，点击完成或测试连通性时会校验组件是否变更
=> [feat_cluster][taier-ui] support change comparison of multi-version components

taier-ui/src/api/index.ts, taier-ui/src/api/reqOffline.ts, taier-ui/src/components/helpDoc/docs.tsx, taier-ui/src/components/icon/index.tsx, taier-ui/src/components/language/index.tsx, taier-ui/src/components/task/open.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/extensions/languages/index.tsx, taier-ui/src/utils/enums.tsx, taier-ui/src/utils/extensions.tsx, taier-ui/src/utils/index.ts
=> [feat_hive][taier-ui]support create hiveSQL

taier-ui/src/extensions/action/index.ts, taier-ui/src/extensions/action/quickRunSQLAction.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/index.ts, taier-ui/src/utils/extensions.tsx
- 支持通过 command+enter 快捷键运行 sql
=> [feat_action][taier-ui]support to execute sql quickly

taier-ui/src/components/dataSync/keymap.tsx, taier-ui/src/components/dataSync/source.tsx, taier-ui/src/components/dataSync/target.tsx
- 修复数据同步任务的问题
- 修复某些数据源不需要请求 tableColumns 但是仍然会请求并报错的问题
- 修复 es 数据源无法搜索的问题
- 修复某些情况下不需要请求 tableList 但仍然请求的问题
- 修复数据预览在某些数据源下没有禁用的问题
- 优化 schema 下拉菜单没有在某些情况下没有初始化的问题
=> [fix_dataSync][taier-ui]fix datasync task

taier-ui/src/components/dataSync/index.scss, taier-ui/src/components/dataSync/keymap.scss, taier-ui/src/components/dataSync/keymap.tsx, taier-ui/src/components/dataSync/modals/constModal.tsx, taier-ui/src/components/task/schedulingConfig/taskDependence.tsx, taier-ui/src/components/task/schedulingConfig/upstreamDependentTasks.tsx, taier-ui/src/pages/index.tsx, taier-ui/src/styles/reset.scss
- 优化 UI 界面
- 优化数据同步任务第三步的主题颜色
- 重构数据同步任务添加常量的模态框
- 优化添加上下游依赖的 UI
=> [fix_ui][taier-ui]improve the ui interface

sql/1.1/1.1_increment.sql, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchTaskService.java
[feat-taier][taier-data-develop] add Hive Task Parameters
=> [feat-taier][taier-data-develop] add Hive Task Parameters

taier-data-develop/src/main/java/com/dtstack/taier/develop/controller/develop/DevelopTaskController.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchTaskService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/vo/develop/query/BatchDataSourceIncreColumnVO.java
[feat-taier][taier-data-develop] add breakpoint continuation
=> [feat-taier][taier-data-develop] add breakpoint continuation

taier-ui/src/api/reqOffline.ts, taier-ui/src/pages/console/cluster/newEdit/index.scss
=> [refactor_req][taier-ui]replace the increColumn request path

taier-ui/src/components/dataSync/index.tsx, taier-ui/src/components/dataSync/target.tsx
- 修复数据同步任务在某些情况下 column 没有变更的问题
=> [fix_dataSync][taier-ui]fix when change sourceId but still have columns in target

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/datasource/impl/DatasourceService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchSparkHiveSqlExeService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchSqlExeService.java
[feat-taier][taier-data-develop]fix sparkVersion
=> [feat-taier][taier-data-develop]fix sparkVersion

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/HadoopDataDownloadService.java
[feat-taier][taier-data-develop]fix hive_select
=> [feat-taier][taier-data-develop]fix hive_select

taier-ui/src/services/executeService.ts
=> [fix_execute][taier-ui]remove log output when execute some command without result

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchTaskService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/schedule/JobService.java
[feat-taier][taier-data-develop]fix sparkHivePublish
=> [feat-taier][taier-data-develop]fix sparkHivePublish

taier-data-develop/src/main/java/com/dtstack/taier/develop/filter/DtRequestWrapperFilter.java
- 请求过滤条件中的白名单定义有误，没有添加全局请求前缀`/taier`导致无法放行
=> fix: upload kerberos (#364) backend error

taier-ui/src/components/mxGraph/index.scss, taier-ui/src/components/slidePane/index.scss, taier-ui/src/pages/operation/taskFlowView/taskGraphView.tsx, taier-ui/src/pages/operation/taskJobFlowView/jobGraphView.tsx, taier-ui/src/styles/common.scss
=> [feat_theme][taier-ui]improve dark theme in jobView

taier-ui/src/components/dataSync/channel.tsx
=> [fix_dirtyData][taier-ui]hide dirtyData for dataSync task

taier-ui/src/api/http.ts, taier-ui/src/components/notification/index.tsx, taier-ui/src/components/notification/notification.scss, taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json, taier-ui/src/pages/dataSource/index.tsx, taier-ui/src/pages/dataSource/search.tsx, taier-ui/src/pages/login.tsx, taier-ui/src/styles/molecule.scss, taier-ui/src/styles/reset.scss
- 优化 message 提示
- 新增 notification 组件用于提示信息
- 修复登陆后选择租户为空的问题
=> [fix_notification][taier-ui]improve the message tips and add a notification

taier-ui/src/api/reqStream.ts, taier-ui/src/api/stream.ts, taier-ui/src/components/editorEntry/index.tsx, taier-ui/src/components/folderPicker/index.tsx, taier-ui/src/components/functionManager/fnModal.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/action/index.ts, taier-ui/src/extensions/action/quickSaveTaskAction.ts, taier-ui/src/extensions/catalogue/index.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/interface.ts, taier-ui/src/services/editorActionBarService.tsx, taier-ui/src/utils/extensions.tsx, taier-ui/src/utils/saveTask.ts
- 支持 FlinkSQL 语法检查功能
- 支持 FlinkSQL 格式化
- 支持创建 FlinkSQL 函数
=> [fix_ui][taier-ui]support flinkSQL

taier-ui/.umirc.ts, taier-ui/src/constant/index.ts, taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/index.tsx, taier-ui/src/utils/enums.tsx
- 新增 ENGINEACCEPTED 状态
- 修复传参问题
=> [fix_status][taier-ui]add task status

taier-ui/src/components/sketch/index.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/hooks/index.ts, taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/index.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/historyLog.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/index.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/index.tsx, taier-ui/src/pages/operation/streamTask/index.tsx, taier-ui/src/styles/reset.scss
- 添加请求参数的兜底，防止接口返回 null 导致页面崩溃
- 优化抽屉样式
- 修复 flinkSQL 和实时采集任务运维跳转错误的问题
- 修复实时任务轮训的问题
=> [fix_ui][taier-ui]improve ui interface

taier-ui/src/api/reqStream.ts, taier-ui/src/api/stream.ts, taier-ui/src/components/slidePane/index.scss, taier-ui/src/constant/index.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/pages/operation/patch/patchModal.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/baseGraph.tsx, taier-ui/src/pages/operation/streamTask/components/goOnTask.tsx, taier-ui/src/pages/operation/streamTask/index.tsx, taier-ui/src/styles/reset.scss
- 支持实时任务停止，续跑等操作
- 优化脚本模式展示 json 格式
=> [fix_ui][taier-ui]support continue running task

taier-ui/src/components/addTenantModal/index.tsx, taier-ui/src/components/detailInfo/index.tsx, taier-ui/src/components/functionManager/fnModal.tsx, taier-ui/src/components/functionManager/fnViewModal.tsx, taier-ui/src/components/functionManager/index.tsx, taier-ui/src/components/graphTime/style.scss, taier-ui/src/components/resourceManager/index.tsx, taier-ui/src/components/resourceManager/resModal.tsx, taier-ui/src/components/resourceManager/resViewModal.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/extensions/init.tsx, taier-ui/src/interface.ts, taier-ui/src/pages/console/cluster/newEdit/components/singleVerComp/index.tsx, taier-ui/src/pages/dataSource/index.tsx, taier-ui/src/pages/login.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/baseGraph.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/index.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/failover.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/index.tsx, taier-ui/src/pages/operation/streamTask/components/goOnTask.tsx, taier-ui/src/pages/rightBar/taskInfo.tsx, taier-ui/src/services/editorActionBarService.tsx, taier-ui/src/services/executeService.ts, taier-ui/src/styles/reset.scss, taier-ui/src/utils/index.ts, taier-ui/src/utils/saveTask.ts
- 新增租户支持中文
- 新增需要填写租户标识
- 函数名称不再限制小写字母
- FlinkSQL 脚本模式支持语法检查
- 修复新增租户后租户列表没有更新的问题
- 优化实时任务续跑任务请求
=> [fix_stream][taier-ui]improve stream task

taier-ui/src/components/streamCollection/source/component/rdb.tsx, taier-ui/src/components/streamCollection/source/dataPreviewModal.tsx, taier-ui/src/extensions/action/index.ts
=> [fix_ui][taier-ui]fix the spells of file's name when importing

taier-ui/src/components/dataSync/index.tsx, taier-ui/src/components/task/taskParams.scss, taier-ui/src/components/task/taskParams.tsx, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/init.tsx
- 修复数据同步任务任务参数无法设置的问题
- 修复加载 antd.dark.css 阻塞的问题
=> [fix_params][taier-ui]fix taskParams in sync task

taier-common/src/main/java/com/dtstack/taier/common/exception/ErrorCode.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/datasource/impl/DatasourceService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/datasource/impl/DsInfoService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchSqlExeService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTenantComponentService.java
修复HiveServer为元数据获取方式，SparkSql无法运行问题
=> [issue_420][taier-all]fix task run

taier-ui/src/components/dataSync/channel.tsx
- 修复数据并发数展示与实际不符的问题
Closed #421
=> [fix_channel][taier-ui]fix channel can't save

taier-ui/src/pages/function/index.tsx
=> [fix_function][taier-ui]fix can't remove function

taier-ui/src/components/helpDoc/docs.tsx, taier-ui/src/components/streamCollection/rightBar/flinkDimension/form.tsx, taier-ui/src/components/streamCollection/rightBar/flinkDimension/index.tsx, taier-ui/src/interface.ts, taier-ui/src/utils/enums.tsx, taier-ui/src/utils/index.ts, taier-ui/src/utils/is.ts
- 重构 flink 维表表单组件
- 修复表单项无法修改的问题
Closed #427
=> [fix_flink][taier-ui]refactor flink dimension form

taier-ui/src/extensions/editor/index.tsx
- 修复转化向导模式后传参不正确的问题
Closed #432
=> [fix_convert][taier-ui]fix tab data not changed after converting

taier-ui/src/components/dataSync/target.tsx
- 修复数据同步任务「主键冲突」在某些数据源下没有屏蔽的问题
Closed #434
=> [fix_writeMode][taier-ui]fix writeMode in oracle and postgresql

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchTaskService.java, taier-ui/src/components/task/open.tsx, taier-ui/src/extensions/action/quickSaveTaskAction.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/folderTree/index.tsx
- 修复在保存后文件夹目录丢失部分数据的问题
- 修复保存后部分状态丢失的问题
Closed #439
=> [fix_edit][taier-ui]fix lost data in folderTree

taier-common/src/main/java/com/dtstack/taier/common/client/ClientOperator.java
deploy session mode appid is null，use EngineTaskId judge task is run ，to stop sycn task
=> [issue_482][taier-all]fix session mode no appid

taier-ui/src/constant/index.ts, taier-ui/src/extensions/init.tsx
=> [fix_colorTheme][taier-ui]fix can't persist colorTheme

taier-ui/src/components/dataSync/keymap.tsx, taier-ui/src/components/dataSync/source.tsx, taier-ui/src/components/dataSync/target.tsx
- 修复数据同步任务数据来源修改数据源部分字段没有重置的问题
- 修复部分数据源的表多选的问题
- 修复分区信息在预览的情况下不展示的问题
- 修复自定义列或常量列没有保存的问题
=> [fix_dataSync][taier-ui]fix dataSync

taier-ui/src/components/streamCollection/rightBar/flinkDimension/index.tsx, taier-ui/src/components/streamCollection/rightBar/flinkSource/index.tsx
- 修复 FlinkSQL 侧边栏在初始化没有下拉菜单的问题
Closed #475
=> [fix_flink][taier-ui]fix rightBar options for flink

sql/1.1/1.1_increment.sql, sql/init.sql, taier-dao/src/main/java/com/dtstack/taier/dao/domain/BatchFunction.java, taier-dao/src/main/java/com/dtstack/taier/dao/domain/BatchResource.java, taier-dao/src/main/java/com/dtstack/taier/dao/mapper/DevelopFunctionDao.java, taier-dao/src/main/resources/sqlmap/DevelopFunctionMapper.xml, taier-dao/src/main/resources/sqlmap/DevelopResourceMapper.xml, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchFunctionService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchResourceService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/vo/develop/result/BatchGetResourceByIdResultVO.java
**简介**
1、修复flinkSQL函数上传路径问题
2、修复flinkSQL 向导udf 函数匹配问题
3、修复自定义函数转化空指针问题
4、优化创建FlinkSQL 自定义函数，选择上传组建限制
Related Issues
#424 
#474 
#425
=> [fix_flink_udf][taier-data-develop]修复flinksql自定义函数问题

taier-ui/src/components/task/schedulingConfig/taskDependence.tsx
=> [fix_dep][taier-ui]fix task name incorrect render in dependencies

taier-ui/src/components/dataSync/index.tsx, taier-ui/src/components/dataSync/preview.tsx, taier-ui/src/components/dataSync/target.tsx, taier-ui/src/components/streamCollection/rightBar/component/customParams.tsx, taier-ui/src/components/streamCollection/rightBar/flinkResult/form.tsx, taier-ui/src/components/streamCollection/rightBar/flinkSource/index.scss, taier-ui/src/constant/index.ts, taier-ui/src/pages/operation/patch/index.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/index.scss, taier-ui/src/pages/operation/streamTask/index.tsx, taier-ui/src/styles/common.scss, taier-ui/src/styles/reset.scss, taier-ui/src/utils/index.ts
- 修复数据同步增量标识任务预览没有显示增量标识的问题
- 修复一些已知样式问题：
1. 数据同步任务目标表名必填但无*标识
2. 离线任务周期过滤项缺失分钟和小时任务
3. 补数据实例列表页dark主题下字段颜色看不清
4. 实时任务详情-数据曲线页面无法上下滚动
5. 实时任务计算中点击停止弹窗按钮错位
6. ellipsis全局样式缺失，导致源表数据预览换行
7. input输入框高度不正确，部分表单元素字体没有统一12px
8. 周期实例详情graph图运行中状态颜色不正确，从绿色改为蓝色
9. 优化实时任务源表和结果表表单样式
=> [fix_1.10_css][taier-ui]fix increment mode not show in edit, fix some css issues

taier-ui/src/pages/function/index.tsx, taier-ui/src/pages/resource/index.tsx, taier-ui/src/services/catalogueService.ts
- 修复资源管理目录的问题
- 修复资源管理编辑的问题
- 修复函数管理编辑文件夹的问题
Closed #502
=> [fix_catalogue][taier-ui]fix function and resource

taier-ui/src/components/task/open.tsx
=> [fix_edit][taier-ui]fix description lost when editing

taier-ui/src/components/task/open.tsx
=> [fix_create][taier-ui]fix getTask when creating task

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/StreamJobMetricService.java
=> [issue_522][taier-data-develop]未提交的任务获取曲线报错修复

taier-scheduler/src/main/java/com/dtstack/taier/scheduler/server/builder/AbstractJobBuilder.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/server/builder/cron/ScheduleCronMinParser.java
[issue_497][taier-scheduler]离线开发补数据生成实例不正确
=> [issue_497][taier-scheduler]离线开发补数据生成实例不正确

taier-ui/src/pages/resource/resModal.tsx
=> [fix_resource][taier-ui]fix can't cover resource

taier-ui/.umirc.ts
- 修复生产环境下加载 worker 失败的问题
Closed #534
=> [build_hash][taier-ui]build hash production ignore worker.js

taier-ui/.umirc.ts
=> [build_env][taier-ui]fix build production in development env

taier-common/src/main/java/com/dtstack/taier/common/constant/PatternConstant.java
[issues_541][taier-common] 自定义函数名校验
=> [issues_541][taier-common] 自定义函数名校验

taier-common/src/main/java/com/dtstack/taier/common/util/JobGraphUtil.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/FlinkTaskVertexGraphService.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/jobdealer/JobSubmittedDealer.java
=> [issues_550][taier]fix:flink拓扑图信息显示不全

taier-ui/src/components/editor/index.tsx
- 修复 editor 组件丢失 placeholder 的问题
Closed #554
=> [fix_placeholder][taier-ui]fix placeholder not work

taier-ui/src/components/dataSync/keymap.tsx
=> [fix_keymap][taier-ui]fix lines dislocations in keymap

taier-ui/src/components/sketch/index.tsx, taier-ui/src/pages/console/cluster/index.tsx, taier-ui/src/pages/console/taskDetail.tsx, taier-ui/src/pages/operation/streamTask/index.tsx
- 修复 sketch 组件调用 submit 会导致页数重置到第一页
- 修复实时任务分页失效
- 修复部分页面修改页数大小无效的问题
#545
=> [fix_submit][taier-ui]fix refresh will reset to first page

taier-ui/src/components/dataSync/source.tsx
- 修复数据源为 Oracle 时， 表名 Select 筛选无效的问题
closed #504
=> fix: add filterOption to Oracle resource

taier-ui/src/components/dataSync/index.tsx, taier-ui/src/components/dataSync/source.tsx, taier-ui/src/components/dataSync/target.tsx
- 修复数据同步任务目标表不存在分区但是仍然必选的问题
- 修复数据同步任务源表分区在某些情况下没有请求的问题
Closed #513  
Closed #512
=> [fix_dataSync][taier-ui]fix dataSync partition

taier-ui/src/components/sketch/index.tsx, taier-ui/src/hooks/index.ts, taier-ui/src/pages/operation/patch/detail.tsx, taier-ui/src/pages/operation/streamTask/index.tsx
- 修复轮询阶段current和pageSize错误的问题，重构polling到request的返回参数中
- 修复usePagination中current、pageSize以及total为0时不赋值的问题
Closed #565
=> [fix_polling][taier-ui]fix polling pagination error

taier-ui/__mocks__/molecule.js, taier-ui/__mocks__/monaco-editor.js, taier-ui/jest.config.js, taier-ui/package.json, taier-ui/pnpm-lock.yaml, taier-ui/scripts/jest-setup.js, taier-ui/src/utils/__tests__/__snapshots__/enums.test.tsx.snap, taier-ui/src/utils/__tests__/enums.test.tsx, taier-ui/src/utils/__tests__/index.test.tsx, taier-ui/src/utils/__tests__/is.test.tsx, taier-ui/src/utils/is.ts
=> [test/utils][taier-ui]add test cases for utils

taier-ui/src/pages/console/cluster/newEdit/formConfig/index.tsx, taier-ui/src/pages/console/cluster/newEdit/interface.ts
=> [feat_cluster][taier-ui]support render tooltip for cluster form field

taier-ui/src/components/bindCommModal/index.tsx, taier-ui/src/components/resourceManageModal/index.tsx, taier-ui/src/pages/console/bindTenant.tsx, taier-ui/src/pages/console/resource.tsx, taier-ui/src/pages/console/resourceView/index.tsx
=> [fix_resource][taier-ui]improve resouce binding tenant

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/context/cluster.ts, taier-ui/src/pages/console/cluster/nextDetail/detail.scss, taier-ui/src/pages/console/cluster/nextDetail/detail.tsx, taier-ui/src/pages/console/cluster/nextDetail/index.scss, taier-ui/src/pages/console/cluster/nextDetail/index.tsx, taier-ui/src/pages/console/cluster/nextDetail/sideBar.scss, taier-ui/src/pages/console/cluster/nextDetail/sideBar.tsx, taier-ui/src/pages/console/cluster/nextDetail/toolbar.tsx, taier-ui/src/pages/index.tsx, taier-ui/src/styles/reset.scss
- 基于 https://github.com/DTStack/Taier/discussions/566 重构控制台
=> [feat/cluster][taier-ui]refactor cluster

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts
=> [fix/queue][taier-ui]fix request lost

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts
=> [fix/queue][taier-ui]fix request lost (#599)

taier-ui/src/components/task/open.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/folderTree/index.tsx
=> [feat/flink][taier-ui]support create flink task

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts
=> [hotfix/request][taier-ui]add lost request

taier-ui/src/extensions/init.tsx
- 支持默认展开任务开发目录
- 修复亮色主题下首次打开没有应用 data-prefers-color 属性
=> [feat_collapse][taier-ui]support expand default collapse

taier-ui/src/pages/console/resource.scss, taier-ui/src/pages/console/resource.tsx, taier-ui/src/pages/console/resourceView/helper.tsx, taier-ui/src/pages/console/resourceView/index.scss, taier-ui/src/pages/console/resourceView/index.tsx
=> [improvement][taier-ui]improve resouce manage

taier-ui/src/components/mxGraph/index.scss, taier-ui/src/extensions/dtstackTheme/index.ts, taier-ui/src/extensions/dtstackTheme/package.json, taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json, taier-ui/src/extensions/index.ts, taier-ui/src/extensions/themes/githubPlus.json, taier-ui/src/extensions/themes/index.tsx, taier-ui/src/global.scss
=> [style/theme][taier-ui]improve colorTheme in light

taier-ui/src/api/http.ts, taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/addTenantModal/index.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/init.tsx, taier-ui/src/pages/account/schemaModal.tsx
=> [feat_schema][taier-ui]support to configurate schema for task component

taier-ui/src/pages/function/index.tsx
=> [feat/function][taier-ui]improve function manager folder

taier-ui/src/extensions/themes/githubPlus.json, taier-ui/src/pages/console/cluster/nextDetail/index.tsx
- 优化接口报错
- 该报错主要是开发阶段的报错，当服务端给出的 template 数据格式不多的时候，会通过 notification 报错，减少服务端排查问题的时间
=> [improvement][taier-ui]have a log when template request incorrect data

taier-ui/public/layout/rightBar.json, taier-ui/src/api/index.ts, taier-ui/src/components/helpDoc/docs.tsx, taier-ui/src/components/lifeCycleSelect/index.tsx, taier-ui/src/interface.ts, taier-ui/src/pages/editor/dataSync/index.tsx, taier-ui/src/pages/rightBar/taskConfig.tsx, taier-ui/src/services/rightBarService.tsx, taier-ui/src/utils/saveTask.ts
- 数据同步任务和数据集成支持任务配置
- 任务配置支持脏数据管理
=> [task_config][taier-ui]support task config in rightbar

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/folderPicker/index.tsx
- 支持通过获取资源路径，来确保总是能够通过资源 id 展示资源名称
=> [feat/resource][taier-ui]support to get resource location

taier-ui/src/services/executeService.ts
- 任务轮训的条件判断优化
- 不再通过 jobId 是否存在去判断是否进行轮训，需要通过 continue 来判断
=> [feat_selectStatus][taier-ui]improve selectStatus

taier-ui/src/extensions/init.tsx
修改内容： 在statusBar下面的未登陆状态位置添加点击登录事件
=> [feat_1.2_addLogin][taier-ui] add loginModal in statusBar

taier-ui/public/layout/create.json, taier-ui/public/layout/editorActions.json, taier-ui/public/layout/rightBar.json, taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/mxGraph/container.tsx, taier-ui/src/components/task/create.tsx, taier-ui/src/extensions/action/quickSaveTaskAction.ts, taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/extensions/themes/githubPlus.json, taier-ui/src/interface.ts, taier-ui/src/layout/index.tsx, taier-ui/src/pages/console/cluster/nextDetail/index.tsx, taier-ui/src/pages/editor/dataSync/index.tsx, taier-ui/src/pages/editor/flink.tsx, taier-ui/src/pages/editor/virtual.tsx, taier-ui/src/pages/editor/workflow/index.scss, taier-ui/src/pages/editor/workflow/index.tsx, taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/common.tsx, taier-ui/src/services/taskRenderService.tsx, taier-ui/src/services/taskSaveService.ts, taier-ui/src/services/viewStoreService.ts
- 支持工作流任务
- 优化任务保存逻辑
- 新增 workflow 组件，为工作流任务做展示
- 新增工作流任务的配置项
=> [feat_workflow_ui][taier-ui]develop workflow task

taier-ui/src/components/task/create.tsx, taier-ui/src/context/index.ts, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/hooks/index.ts, taier-ui/src/pages/console/cluster/nextDetail/index.tsx, taier-ui/src/pages/console/cluster/nextDetail/sideBar.tsx, taier-ui/src/pages/index.tsx
- 优化 typo
- 优化应用支持的任务列表请求，支持 dispatch
- 修复修改计算组件后，没有重新获取任务支持列表的问题
- 修复新增任务的 tab 切换后数据没有回填的问题
=> fix: support dispatch support jobs in cluster

taier-ui/src/pages/console/resource.tsx
=> fix: support show tenant list without engine

taier-data-develop/src/main/java/com/dtstack/taier/develop/controller/develop/DevelopTaskController.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/dto/devlop/TaskVO.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopCatalogueService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTaskService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/vo/develop/query/DevelopTaskNameCheckVO.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/vo/develop/query/DevelopTaskResourceParamVO.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/service/ScheduleTaskTaskService.java
=> Conflict feat 1.2 work flow

taier-ui/src/components/task/publish.tsx, taier-ui/src/extensions/editor/index.tsx
=> fix: publish no longer need description

taier-ui/src/components/mxGraph/container.tsx, taier-ui/src/components/mxGraph/index.tsx, taier-ui/src/components/task/publish.tsx, taier-ui/src/extensions/themes/githubPlus.json, taier-ui/src/extensions/themes/index.tsx, taier-ui/src/interface.ts, taier-ui/src/pages/editor/workflow/index.scss, taier-ui/src/pages/editor/workflow/index.tsx, taier-ui/src/services/taskSaveService.ts
- 优化工作流主题色
- 优化提交文案
- 修复工作流添加失败的问题
=> [refactor][taier-ui]improve workflow vertex theme

taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/pages/console/cluster/detail/index.tsx, taier-ui/src/pages/rightBar/flinkDimension/form.tsx, taier-ui/src/pages/rightBar/flinkDimension/index.tsx, taier-ui/src/pages/rightBar/flinkResult/form.tsx, taier-ui/src/pages/rightBar/flinkResult/index.tsx, taier-ui/src/services/taskSaveService.ts
- 修复 flinksql 保存失败的问题
- 修复工作流无法删除任务的问题
- 修复控制台集群无法新增组件后请求失败的问题
=> [fix/flinksql][taier-ui]fix flinksql save failed

taier-ui/src/components/detailInfo/index.tsx, taier-ui/src/components/folderPicker/customTreeSelect.tsx, taier-ui/src/components/folderPicker/index.tsx, taier-ui/src/components/scaffolds/create.tsx, taier-ui/src/components/task/create.tsx, taier-ui/src/components/task/editFolder.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/pages/function/fnModal.tsx, taier-ui/src/pages/function/folderModal.tsx, taier-ui/src/pages/function/index.tsx, taier-ui/src/pages/operation/streamTask/index.tsx, taier-ui/src/pages/operation/task.tsx, taier-ui/src/pages/resource/index.tsx, taier-ui/src/pages/resource/resModal.tsx, taier-ui/src/pages/rightBar/taskInfo.tsx, taier-ui/src/services/breadcrumbService.ts, taier-ui/src/services/catalogueService.ts, taier-ui/src/utils/extensions.tsx
- 优化错误拼写
- 支持新增 hivesql 函数
- 修复实时任务采集在某些情况下无法展示任务类型的问题
=> [feat/function][taier-ui]support to create hivesql function

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/mxGraph/container.tsx, taier-ui/src/components/mxGraph/index.scss, taier-ui/src/components/sketch/index.tsx, taier-ui/src/interface.ts, taier-ui/src/pages/operation/patch/detail.tsx, taier-ui/src/pages/operation/schedule.tsx, taier-ui/src/pages/operation/task.tsx, taier-ui/src/pages/operation/taskFlowView/index.tsx, taier-ui/src/pages/operation/taskJobFlowView/index.tsx, taier-ui/src/utils/index.ts
- 运维中心任务管理支持工作流
- 运维中心补数据实例支持工作流
=> [feat/workflow][taier-ui]support workflow job and task in operation

taier-ui/src/pages/console/queue.tsx, taier-ui/src/pages/console/taskDetail.tsx
=> fix: improve table width in queue

taier-ui/src/pages/rightBar/schedulingConfig/index.tsx, taier-ui/src/pages/rightBar/schedulingConfig/scheduleForm.tsx
=> fix: prevent workflow related task change schedule config

taier-ui/package.json, taier-ui/pnpm-lock.yaml, taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/mxGraph/index.scss, taier-ui/src/components/mxGraph/index.tsx, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/themes/defaultDark.json, taier-ui/src/extensions/themes/defaultLight.json, taier-ui/src/extensions/themes/index.tsx, taier-ui/src/layout/index.tsx, taier-ui/src/pages/editor/workflow/index.tsx, taier-ui/src/pages/operation/patch/detail.tsx, taier-ui/src/pages/operation/schedule.tsx, taier-ui/src/pages/operation/taskFlowView/index.tsx, taier-ui/src/pages/operation/taskJobFlowView/index.scss, taier-ui/src/pages/operation/taskJobFlowView/index.tsx, taier-ui/src/pages/rightBar/taskConfig.tsx, taier-ui/src/services/taskSaveService.ts, taier-ui/src/utils/index.ts
- 升级 antd 的版本
- 优化请求接口
- 优化 theme 主题色
- 修复工作流保存的问题
- 修复工作流调度周期没有同步的问题
- 修复工作流的展示问题
=> [fix/workflow][taier-ui]fix workflow save

taier-ui/src/components/editor/index.tsx, taier-ui/src/components/editor/language/jsonlog.ts, taier-ui/src/extensions/themes/defaultDark.json, taier-ui/src/extensions/themes/defaultLight.json
- 优化滚动条的 theme 样式
- 优化 editor 的实例
Closed #494
=> [fix/theme][taier-ui]improve scroll theme

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/console/ConsoleComponentService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/console/ConsoleService.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/service/ComponentService.java
I fixed the NPE problem when test connection to comment hiveserver.The issus address is https://github.com/DTStack/Taier/issues/655
=> [issue_655][taier-scheduler] fix wrapperConfig componentType HIVE_SERVER fix #655

taier-ui/src/api/http.ts, taier-ui/src/context/index.ts, taier-ui/src/hooks/index.ts, taier-ui/src/pages/index.tsx
=> fix: improve support job get after saving cluster

taier-ui/src/api/request.ts
- 修复按照业务日期杀任务失败的问题
Closed #524
=> fix: fix can't stop job by date

taier-ui/src/pages/console/cluster/detail/index.tsx
- 修复 kerberos 文件保存后仍然丢失的问题
Closed #661
=> [fix/kerberos][taier-ui]fix kerberos file lost

website/docs/quickstart/deploy/web.md
- 更新 web 部署文档，移除 mini-cup 和 Node.js 等相关环境的安装步骤，直接让用户通过 nginx + dist 文件部署
=> [docs_web][website]update web deploy doc

taier-worker/taier-plugins/schedules/yarn-core/src/main/java/com/dtstack/taier/yarn/DtYarnClient.java
=> add parser of fair scheduler from yarn scheduler API

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTaskService.java
- 修复已配置依赖关系的任务，无法发布到调度的问题。
#676
=> fix publishTaskInfo (#676)

taier-ui/package.json, taier-ui/pnpm-lock.yaml, taier-ui/src/components/editor/config.ts, taier-ui/src/extensions/action/quickSaveTaskAction.ts, taier-ui/src/services/taskRenderService.tsx, taier-ui/src/utils/enums.tsx
- 侧边栏支持展示默认值
- 编辑器按钮支持展示默认值
- 修复语法没有高亮的问题
- 离线任务的默认值是「任务属性」「调度配置」「环境参数」「任务参数」
- 实时任务的默认值是「任务属性」
- 离线任务的默认值是「保存」「运行」「停止运行」「提交」
- 实时任务的默认值是「保存」「提交」
- 所有二开的任务语法高亮以 SQL 为基准，如果有需求需要自行开发
=> [fix/default][taier-ui]change the default sidebar for tasks

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/schedule/ActionService.java
=> fix: password filter in the instance's logs

taier-ui/src/services/taskRenderService.tsx
=> [fix/actions][taier-ui]fix default editor actions for stream task

taier-ui/src/pages/dataSource/selectSource.tsx
=> [fix/datasource][taier-ui]pass through a string for query data source

taier-ui/.gitignore, taier-ui/src/pages/editor/dataSync/modals/keyModal.tsx, taier-ui/src/utils/__tests__/enums.test.tsx, taier-ui/src/utils/__tests__/index.test.tsx, taier-ui/src/utils/index.ts
=> [fix/keymap][taier-ui]fix utils function import

taier-ui/src/components/mxGraph/index.scss, taier-ui/src/components/mxGraph/index.tsx, taier-ui/src/pages/operation/taskFlowView/index.tsx, taier-ui/src/pages/operation/taskJobFlowView/index.scss, taier-ui/src/styles/common.scss, taier-ui/src/styles/theme.scss, taier-ui/src/utils/index.ts
=> [fix/cssVariables][taier-ui]improve css styles

taier-ui/src/utils/__tests__/enums.test.tsx, taier-ui/src/utils/enums.tsx
=> [fix/highlight][taier-ui]fix syntax highlight

taier-ui/src/pages/editor/workflow/index.scss, taier-ui/src/pages/rightBar/index.scss, taier-ui/src/styles/theme.scss
=> [fix/theme][taier-ui]improve workflow theme

taier-ui/__mocks__/molecule.js, taier-ui/__mocks__/monaco-editor.js, taier-ui/jest.config.js, taier-ui/src/utils/__tests__/__snapshots__/extensions.test.tsx.snap, taier-ui/src/utils/__tests__/__snapshots__/index.test.tsx.snap, taier-ui/src/utils/__tests__/extensions.test.tsx, taier-ui/src/utils/__tests__/index.test.tsx, taier-ui/src/utils/extensions.tsx
=> [test][taier-ui]improve test coverage

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/pages/editor/dataSync/index.tsx, taier-ui/src/pages/rightBar/flinkDimension/form.tsx, taier-ui/src/pages/rightBar/flinkResult/form.tsx, taier-ui/src/pages/rightBar/flinkSource/form.tsx, taier-ui/src/services/taskRenderService.tsx
=> [feat/support][taier-ui]get supported source from request

taier-ui/src/services/executeService.ts
=> [fix/dataSync][taier-ui]fix stop dataSync

taier-ui/__mocks__/molecule.js, taier-ui/src/services/__tests__/__snapshots__/catalogueService.test.ts.snap, taier-ui/src/services/__tests__/__snapshots__/editorActionBarService.test.ts.snap, taier-ui/src/services/__tests__/breadcrumbService.test.ts, taier-ui/src/services/__tests__/catalogueService.test.ts, taier-ui/src/services/__tests__/dataSourceService.test.ts, taier-ui/src/services/__tests__/editorActionBarService.test.ts, taier-ui/src/services/__tests__/functionManagerService.test.ts
=> [test/services][taier-ui]improve test coverage

taier-ui/src/pages/rightBar/taskParams.scss, taier-ui/src/pages/rightBar/taskParams.tsx
1. 添加文字溢出隐藏，并添加 Tooltip 用来展示全部 ， #757
=> [fix/ellipsis][taier-ui]fix text ellipsis in taskParams (#757)

taier-ui/.umirc.ts, taier-ui/src/components/scaffolds/create.tsx, taier-ui/src/components/task/create.tsx, taier-ui/src/constant/index.ts, taier-ui/src/extensions/languages/index.tsx, taier-ui/src/interface.ts, taier-ui/src/services/taskRenderService.tsx, taier-ui/src/utils/enums.tsx
=> [feat/task][taier-ui]support python and shell task

taier-ui/src/pages/editor/workflow/index.tsx, taier-ui/src/services/taskSaveService.ts
- 修复数据同步任务在脚本模式下保存失败的问题
- 优化工作流显示未知任务的问题
=> [fix/save][taier-ui]fix save sync task in script mode

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/scaffolds/create.tsx, taier-ui/src/context/index.ts, taier-ui/src/interface.ts, taier-ui/src/pages/dataSource/index.tsx, taier-ui/src/pages/dataSource/search.tsx, taier-ui/src/services/dataSourceService.ts, taier-ui/src/services/index.ts
=> [feat/datasource][taier-ui]develop datasource when creating task

taier-ui/src/components/scaffolds/create.tsx, taier-ui/src/extensions/languages/index.tsx, taier-ui/src/utils/extensions.tsx
=> [fix/worker][taier-ui]improve python worker

taier-ui/src/components/mxGraph/container.tsx, taier-ui/src/pages/editor/workflow/index.tsx, taier-ui/src/services/taskSaveService.ts
- 修复工作流任务在某些情况下会丢失连线的问题
Closed #780
=> [fix/workflow][taier-ui]fix lost line in workflow

taier-ui/src/extensions/folderTree/index.tsx, taier-ui/src/services/taskSaveService.ts
- 修复 flink 任务在某些情况下会丢失保存内容的问题
Closed #785
=> [fix/flink][taier-ui]fix flink tab saving

taier-ui/package.json, taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/scaffolds/create.tsx, taier-ui/src/pages/editor/spark.tsx, taier-ui/src/services/taskSaveService.ts
- 支持 spark 任务
- 优化引擎版本物料的更新
- 优化资源物料
=> [feat/sparkjar][taier-ui]support sparkjar task

taier-ui/src/hooks/index.ts
=> [fix/usePagination][taier-ui]fix pagination get incorrect

taier-ui/src/components/scaffolds/create.tsx, taier-ui/src/pages/function/fnModal.tsx, taier-ui/src/pages/resource/resModal.tsx, taier-ui/src/services/resourceManagerService.ts
- 修复资源校验文件夹在某些情况下失效的问题
Closed #788
=> [fix/validator][taier-ui]fix validator folder failed in resource

taier-ui/src/services/taskRenderService.tsx
=> [fix/default][taier-ui]remove default actions and barItems

taier-ui/src/components/folderPicker/customTreeSelect.tsx, taier-ui/src/components/scaffolds/create.tsx, taier-ui/src/components/task/create.tsx
=> feat: improve popup in create

taier-ui/src/utils/index.ts
=> [fix/splitKey][taier-ui]support to get splitKey in array

taier-ui/src/components/detailInfo/index.tsx, taier-ui/src/interface.ts
=> [feat/taskInfo][taier-ui]support to show dataSource in task info tab

taier-ui/src/pages/rightBar/schedulingConfig/index.tsx
=> [fix/scheduleConf][taier-ui]fix selfReliance won't change

taier-ui/src/pages/console/cluster/detail/index.tsx, taier-ui/src/services/taskRenderService.tsx
- 优化集群保存后，对支持 job 列表的静默操作
- 修复新增加的集群无法删除的问题
=> [fix/cluster][taier-ui]improve cluster save

taier-ui/src/components/previewTable/index.tsx, taier-ui/src/constant/index.ts, taier-ui/src/services/taskSaveService.ts
- 优化预览数据 table 的样式
- 优化 flinksql 的保存逻辑
=> [refactor/preview][taier-ui]improve preview table

taier-data-develop/src/main/java/com/dtstack/taier/develop/vo/develop/result/DevelopFunctionQueryResultVO.java, taier-ui/src/pages/function/index.tsx
=> [issue#798][taier-data-develop] flink udf 回显不正确

taier-ui/src/components/scaffolds/create.tsx
=> [fix/componentVersion][taier-ui]improve componentVersion label

taier-ui/src/pages/console/cluster/detail/index.tsx, taier-ui/src/pages/console/cluster/detail/toolbar.tsx
=> [fix/cluster][taier-ui]support more impressive error log

taier-ui/src/services/executeService.ts, taier-ui/src/utils/extensions.tsx
=> [fix/execute][taier-ui]fix log output panel after executing

taier-worker/taier-worker-plugin/flink/common/pom.xml
Upgrade 'flink.version' to 1.12.7.
=> [Improve][Common] Upgrade 'flink.version' to 1.12.7

taier-ui/src/pages/operation/streamTask/index.tsx
=> [fix/stream][taier-ui]remove component version filters in stream

taier-ui/src/pages/rightBar/flinkDimension/index.tsx, taier-ui/src/pages/rightBar/flinkResult/index.tsx, taier-ui/src/pages/rightBar/flinkSource/index.tsx
- 修复在某些情况下删除了 flinksql 的表后仍然会去校验数据的问题
Closed #829
=> [fix/flink][taier-ui]fix validation on flinksql

.gitignore, build/mvn-build-datadevelop.sh, build/mvn-build.sh, pom.xml, taier-data-develop/pom.xml, taier-data-develop/src/main/java/com/dtstack/taier/develop/config/MvcConfig.java, taier-ui/.umirc.ts, taier-ui/README.md, taier-ui/pom.xml
added ui build method(#851 ) and integrate front-end resources into taier-data-develop to complete single-point deployment and operation of the back-end, solving cross-domain and deployment difficulties
=> build: reset ui build

taier-worker/taier-worker-plugin/spark/yarn2-hdfs2-spark210-core/spark-yarn-client-core/src/main/java/com/dtstack/taier/sparkyarn/sparkyarn/SparkYarnClient.java, taier-worker/taier-worker-plugin/spark/yarn2-hdfs2-spark210-core/spark-yarn-client-core/src/main/java/com/dtstack/taier/sparkyarn/sparkyarn/SparkYarnResourceInfo.java, taier-worker/taier-worker-plugin/spark/yarn2-hdfs2-spark210-core/spark-yarn-client-core/src/main/java/com/dtstack/taier/sparkyarn/sparkyarn/file/ResourceCleaner.java, taier-worker/taier-worker-plugin/spark/yarn2-hdfs2-spark210-core/spark-yarn-client-core/src/main/java/com/dtstack/taier/sparkyarn/sparkyarn/file/SparkResourceUploader.java
增加spark uploader 用于传输spark-sql-proxy.jar
=> [feat_863][taier-worker-plugin] spark sql proxy auto upload

taier-ui/src/constant/index.ts, taier-ui/src/pages/console/cluster/detail/detail.tsx
=> [feat/cluster][taier-ui]improve description label in cluster's uploader

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/datasource/impl/DatasourceService.java
=> [hotfix_datasource][taier-data-develop] fix datasource update time

taier-ui/src/interface.ts, taier-ui/src/pages/operation/schedule.tsx
=> [fix/schedule][taier-ui]support render deleted task in schedule

taier-ui/pom.xml
remove yarn download proxy mirrors
=> fixed: the ui project cannot download yarn

taier-data-develop/src/main/java/com/dtstack/taier/develop/service/schedule/JobService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/vo/schedule/ReturnJobListVO.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/server/scheduler/AbstractJobScanningScheduler.java
[issue_669][taier-data-develop]show schedule job name when task is deleted; scheduling job to autoCanceled rather than submitFaild if task is deleted
=> [issue_669][taier-data-develop]show schedule job name when task is deleted; scheduling job to autoCanceled rather than submitFaild if task is deleted

taier-ui/src/pages/rightBar/envParams.tsx
- 修复环境变量在某些情况下无法编辑的问题
closed #907
=> [fix/envParams][taier-ui]fix cursor always in first time on envParams

taier-ui/src/pages/dataSource/add.tsx
=> [fix/testConn][taier-ui]fix message.error in twice

taier-ui/src/api/index.ts, taier-ui/src/api/request.ts, taier-ui/src/components/lineTo/index.tsx, taier-ui/src/components/scaffolds/task.tsx, taier-ui/src/constant/index.ts, taier-ui/src/interface.ts, taier-ui/src/pages/editor/dataSync/index.tsx, taier-ui/src/pages/editor/dataSync/keyMap.scss, taier-ui/src/pages/editor/dataSync/keyMap.tsx, taier-ui/src/pages/editor/dataSync/modals/keyModal.tsx, taier-ui/src/pages/editor/dataSync/tableFooter.scss, taier-ui/src/pages/editor/dataSync/tableFooter.tsx, taier-ui/src/services/taskSaveService.ts
- 数据同步任务支持 FTP 的输入和输出端
#897 
Please make sure acesss this PR with #915
=> [feat/ftp][taier-ui]support ftp in reader and writer

sql/1.3.1/increment.sql, taier-data-develop/src/main/java/com/dtstack/taier/develop/enums/develop/FlinkVersion.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/flink/sql/GuideTableParamsUtil.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/flink/sql/SqlGenerateFactory.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/flink/sql/core/SqlParamUtil.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTaskService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/FlinkTaskService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/saver/AbstractTaskSaver.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/saver/FlinkSqlTaskSaver.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/saver/FlinkTaskSaver.java
- 修复新建任务环境参数丢失
- flink 版本切换为数据库转换
=> [issue_939][taier-data-develop] fix new task lost task param fix #939

taier-ui/src/components/scaffolds/task.tsx, taier-ui/src/interface.ts, taier-ui/src/pages/editor/dataSync/keyMap.tsx
- 修复数据同步任务 FTP 数据源获取唯一值字段的问题
Closed #938
=> fix: table render in FTP target

taier-ui/src/extensions/editor/index.tsx
=> [refactor][taier-ui]parse task variables by editor's value in default

taier-ui/src/utils/__tests__/enums.test.tsx, taier-ui/src/utils/__tests__/index.test.tsx, taier-ui/src/utils/enums.tsx, taier-ui/src/utils/index.ts
=> [style/utils][taier-ui]remove unused functions

taier-ui/src/extensions/folderTree/index.tsx
- 修复在某些情况下创建文件夹失败的问题
Closed #952
=> [fix/create][taier-ui]fix create folder failed

taier-ui/src/pages/rightBar/schedulingConfig/upstreamDependentTasks.tsx, taier-ui/src/styles/reset.scss
- 优化上下游依赖的任务下拉菜单没有默认值的问题
- 优化暗黑主题下的错误提示样式
=> [refactor/upstream][taier-ui]improve the upstream default options

taier-ui/src/context/index.ts, taier-ui/src/interface.ts, taier-ui/src/services/taskRenderService.tsx, taier-ui/src/utils/extensions.tsx
- Support run sql in selections
Closed #924
=> [feat/selection][taier-ui]support run sql in selection

taier-datasource/taier-datasource-plugin/taier-datasource-plugin-clickhouse/src/main/java/com/dtstack/taier/datasource/plugin/clickhouse/ClickHouseDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-db2/src/main/java/com/dtstack/taier/datasource/plugin/db2/Db2Downloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-dm/src/main/java/com/dtstack/taier/datasource/plugin/dm/DmDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-greenplum6/src/main/java/com/dtstack/taier/datasource/plugin/greenplum/GreenplumDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-kylin/src/main/java/com/dtstack/taier/datasource/plugin/kylin/KylinDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-libra/src/main/java/com/dtstack/taier/datasource/plugin/libra/LibraDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-mysql5/src/main/java/com/dtstack/taier/datasource/plugin/mysql5/MysqlDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oceanbase/src/main/java/com/dtstack/taier/datasource/plugin/oceanbase/OceanBaseDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/OracleDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-postgresql/src/main/java/com/dtstack/taier/datasource/plugin/postgresql/PostgresqlDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-sap_hana/src/main/java/com/dtstack/taier/datasource/plugin/saphana/SapHanaDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-sqlserver/src/main/java/com/dtstack/taier/datasource/plugin/sqlserver/SqlServerDownloader.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-trino/src/main/java/com/dtstack/taier/datasource/plugin/trino/download/TrinoDownloader.java
Improve the datasource code.  Use automatic resource management to replace 'try - finally' code block.
=> [Improve][DataSource] Use automatic resource management to replace 'try - finally' code block.

taier-ui/src/components/confirm/index.scss, taier-ui/src/components/confirm/index.tsx, taier-ui/src/extensions/auxiliaryBar/index.tsx, taier-ui/src/extensions/confirm/index.tsx, taier-ui/src/extensions/editor/index.tsx, taier-ui/src/extensions/index.ts, taier-ui/src/utils/extensions.tsx, taier-ui/src/utils/index.ts
- fix editor's actions and editor's auxiliary bar not related to current task
- add confirm before unsaved task tab
Closed #459
=> [feat/close][taier-ui] improve close tab related event handler

taier-ui/src/components/detailInfo/index.tsx, taier-ui/src/pages/console/queue.tsx, taier-ui/src/pages/dataSource/index.tsx
-  remove warning message in devtool console
=> [refactor/warning][taier-ui] remove warning message in devtool console

taier-common/src/main/java/com/dtstack/taier/common/enums/EScheduleJobType.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopScriptService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/runner/DataXTaskRunner.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/saver/DataXTaskSaver.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/saver/ScriptTaskSaver.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/utils/develop/CreateJsonFileUtil.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/service/ScheduleActionService.java
=> [feat_1.3][taier-datax][add datax]

taier-ui/package.json
=> [fix/dependency][taier-ui]lock @dtinsight/molecule's version

bin/taier.sh
(cherry picked from commit 707c92779994dad76b3a0f900806c42df290dd2f)
=> [script][taier-script] fix start script not check dir

taier-ui/src/constant/index.ts, taier-ui/src/services/taskRenderService.tsx
=> [feat/hadoopMR][taier-ui]support hadoopMR icon

taier-ui/src/services/executeService.ts
=> [fix/execute][taier-ui]fix get same jobId when execute sql repeat

sql/1.4/increment.sql, taier-common/src/main/java/com/dtstack/taier/common/client/ClientCache.java, taier-common/src/main/java/com/dtstack/taier/common/client/ClientFactory.java, taier-common/src/main/java/com/dtstack/taier/common/enums/EComponentType.java, taier-common/src/main/java/com/dtstack/taier/common/enums/EScheduleJobType.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopScriptService.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/runner/DataXTaskRunner.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/saver/DataXTaskSaver.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/service/DataxService.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/service/ScheduleActionService.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/utils/CreateJsonFileUtil.java, taier-worker/taier-worker-api/src/main/java/com/dtstack/taier/pluginapi/constrant/ConfigConstant.java
[feat_datax_1][taier-datax][change datax into engine]
=> [feat_datax_1][taier-datax][change datax into engine]

taier-ui/src/pages/console/cluster/detail/sideBar.tsx
=> [feat/console][taier-ui]improve multiple version render

taier-datasource/taier-datasource-plugin/taier-datasource-plugin-common/src/main/java/com/dtstack/taier/datasource/plugin/common/sftp/SFTPHandler.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-common/src/main/java/com/dtstack/taier/datasource/plugin/common/utils/PathUtils.java, taier-worker/taier-worker-api/src/main/java/com/dtstack/taier/pluginapi/constrant/ConfigConstant.java
=> fixed: 系统兼容性(#964)不同系统数据文件分割符问题

taier-dao/src/main/resources/sqlmap/ComponentMapper.xml
=> [feat_mapper][taier_dao] fix "getByVersionName" sql

taier-ui/src/utils/completion.ts
=> [improve/keywords][taier-ui]prevent duplicated fetch for keywords

taier-ui/src/services/__tests__/__snapshots__/rightBarService.test.tsx.snap, taier-ui/src/services/__tests__/rightBarService.test.tsx, taier-ui/src/services/rightBarService.tsx
=> [fix/dep][taier-ui]fix dep render undefined

sql/1.4/increment.sql, sql/init.sql
[feat_datax_bug][sql] fix datax bug about datasource-mapping.json
=> [feat_datax_bug][sql] fix datax bug about datasource-mapping.json

taier-ui/src/pages/rightBar/taskConfig.tsx
=> [refactor/taskConfig][taier-ui]unify the get of dataSource

taier-datasource/taier-datasource-plugin/taier-datasource-plugin-s3/pom.xml, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-s3/src/main/java/com/dtstack/taier/datasource/plugin/s3/S3Client.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-s3/src/main/java/com/dtstack/taier/datasource/plugin/s3/S3Utils.java, taier-datasource/taier-datasource-plugin/taier-datasource-plugin-s3/src/main/resources/META-INF/services/com.dtstack.taier.datasource.api.client.IClient
I just copy the s3 datasource plugin code from `DTStack/DatasourceX` project to solve issue 1073.
=> [issue_1073][taier-datasource] fix create s3 datasource error(#1073) 

taier-ui/src/services/__tests__/__snapshots__/taskSaveService.test.ts.snap, taier-ui/src/services/__tests__/taskSaveService.test.ts, taier-ui/src/services/taskSaveService.ts
- 修复 flinkjar 在某些情况下保存失败的问题
Closed #1079
=> [fix/save][taier-ui]fix flinkjar task save failed

sql/1.4/1.4_increment.sql, sql/init.sql, taier-data-develop/src/main/java/com/dtstack/taier/develop/model/system/Context.java, taier-data-develop/src/main/java/com/dtstack/taier/develop/service/schedule/ActionService.java, taier-worker/taier-worker-api/src/main/java/com/dtstack/taier/pluginapi/constrant/ConfigConstant.java
[feat_datax_conflict_bug][sql] fix datax bug about conflict
=> [feat_datax_conflict_bug][sql] fix datax bug about conflict

taier-scheduler/src/main/java/com/dtstack/taier/scheduler/jobdealer/JobStatusDealer.java, taier-scheduler/src/main/java/com/dtstack/taier/scheduler/jobdealer/JobStopDealer.java
#1103 解决RDB SQL 执行中 进程重启 任务状态卡死 不结束问题
=> [master_0804_fix_issue_1103][scheduler][fix issue 1103]

taier-ui/src/pages/console/cluster/detail/index.tsx
🔗 相关 Issue
feat https://github.com/DTStack/Taier/issues/1135
解决集群配置删除部分无效key-value值后,重新上传不更新，保存无法生效的问题
=> [issue_1135][tail-ui] fix The uploaded yarn configuration is not refreshed

taier-dao/src/main/resources/sqlmap/ScheduleJobCacheMapper.xml
Fixed API `/taier/api/console/listNames` SQL Injection Vulnerabilities (#1184)
=> Fixed SQL Injection Vulnerabilities (#1184)
