DTStack/Taier

- taier-ui/cup.config.js
> [taier-ui] remove the useless slash in publicURL

- taier-common/src/main/java/com/dtstack/taier/common/util/SystemPropertyUtil.java
System path separator not compatible with Windows
> fixed: System path separator not compatible with Windows

- taier-ui/package.json
- taier-ui/src/api/reqOffline.ts
- taier-ui/src/pages/index.tsx
- taier-ui/src/styles/reset.scss
- 移除 @ant-design/compatible 依赖
- 移除 'antd/dist/antd.less'， 因为 umi 架构的项目会自动引入 antd，不需要重复引入
- @ant-design/compatible 这个依赖的 icon 和 form 都重构了，所以可以放心移除
> [fix_style][taier-ui]remove @ant-design/compatible

- taier-ui/src/components/customHooks/useCalcTableScroll.ts
- 修复当 table 没有 header 或者 footer 的时候，页面会崩溃的问题
- `querySelector` 方法用范型给类型而不是通过 as 断言
- 优化当找不到元素的时候给 0 兜底
- prettier code style
> [fix_tableScroller][taier-ui]fix break when table without header or footer

- taier-ui/src/pages/operation/task.tsx
> [fix_task][taier-ui]fix can't filter periodType in task operation

- taier-ui/src/components/dataSync/index.tsx
- taier-ui/src/components/folderPicker/index.tsx
- taier-ui/src/components/task/editFolder.tsx
- taier-ui/src/constant/index.ts
- taier-ui/src/extensions/catalogue/index.ts
- taier-ui/src/extensions/folderTree/index.tsx
- taier-ui/src/pages/console/resource.tsx
- taier-ui/src/pages/function/index.tsx
- taier-ui/src/pages/resource/index.tsx
- taier-ui/src/pages/resource/resModal.tsx
- taier-ui/src/services/breadcrumbService.ts
- taier-ui/src/services/catalogueService.ts
- taier-ui/src/services/index.ts
- taier-ui/src/utils/extensions.tsx
- 修复目录树重命名的问题
- 修复面包屑在重命名后没有更新的问题
- 修复数据同步任务点击保存没有更新 tab 状态的问题
- 抽离一个 catalogueService 把全局对目录树的操作都收敛到该 service 中
- 抽离一个 breadcrumbService 把全局对面包屑组件数据的生成操作都收敛
- 暂时移除重命名的 contextMenu，目前重命名仅支持编辑打开 tab 进行修改
> [issue_466][taier-ui]fix folderTree

- taier-ui/src/extensions/editor/index.tsx
- 修复运行中和停止运行按钮在disable的状态下仍然可以点击，并且发送了请求
Closed #564
> [fix_operation][taier-ui]fix disabled buttons can still be clicked

- taier-ui/.umirc.ts
- taier-ui/src/api/http.ts
- taier-ui/src/api/index.ts
- taier-ui/src/extensions/languages/index.tsx
- taier-ui/src/pages/editor/dataSync/keymap.tsx
- taier-ui/src/pages/editor/dataSync/source.tsx
- taier-ui/src/pages/editor/dataSync/target.tsx
- taier-ui/src/services/taskRenderService.tsx
- 数据同步任务支持中断请求
- 优化异步渲染
- 新增 sql.worker.js 
- 数据同步任务的接口有时候需要查询很久，用户关闭数据同步任务的 tab 后仍然在 pending 请求，会导致其他请求挂起，所以需要在关闭数据同步任务后把 pending 的请求 cancel 了
- 通过 lazy 和 suspend 组件优化组件的异步渲染
> fix: support abort request in dataSync

- taier-ui/src/components/editorEntry/index.tsx
产生问题： window 的keybindings出现“Ctril”进行split，导致分割符展示；
修复： 通过正则匹配，如果匹配到，将Ctril字段提取出来，剩下的字符串进行split
Closed #555
> [fix_1.2][taier-ui]: fix window Ctrl split #555

- taier-data-develop/src/main/java/com/dtstack/taier/develop/service/datasource/impl/DatasourceService.java
`Build data source metadata object` tenant ID is repeatedly written
> chore: remove invalid duplicate data write object

- taier-ui/package.json
- taier-ui/pnpm-lock.yaml
- 升级 antd 的版本
Sourced from [antd's changelog](https://github.com/ant-design/ant-design/releases)
Closed #663
> build(deps): bump antd from 4.21.x to 4.22.x

- taier-ui/src/utils/extensions.tsx
前提：当某项任务执行过，面板已经打开。
复现： 当该任务再次执行，该面板数据未被更新。
判断存在该面板后，将执行后的数据更新到当前面板上。
>   [fix][taier-ui] runTask to update value when panel exist (#725)

- taier-ui/src/components/folderPicker/customTreeSelect.tsx
- 修复存储位置在某些情况下会出现工作流的问题
Closed #787
> [fix/folderPicker][taier-ui]fix folderPicker with workflow

- taier-ui/src/components/scaffolds/create.tsx
- taier-ui/src/components/task/create.tsx
- taier-ui/src/extensions/folderTree/index.tsx
- taier-ui/src/pages/editor/workflow/index.tsx
- 优化数据源必填项校验失败的问题
- rename type
- 优化工作流任务保存的校验逻辑
Closed #794
> [fix/workflow][taier-ui]fix workflow repeated name in validating

- taier-ui/src/pages/editor/streamCollection/source/component/tablePreview.tsx
- taier-ui/src/pages/editor/streamCollection/source/dataPreviewModal.tsx
- taier-ui/src/pages/rightBar/flinkSource/form.tsx
- taier-ui/src/utils/index.ts
- 修复 flinkSQL 源表字段解析在某些情况下错误的问题
- 优化数据预览的 UI
Closed #815
> [fix/flinkSource][taier-ui]fix flinkSource alias

- taier-worker/taier-worker-plugin/script/yarn2-hdfs2-script/script-core/pom.xml
- taier-worker/taier-worker-plugin/script/yarn3-hdfs3-script/script-core/pom.xml
修复script 插件构建时，script-core的jar 位置错位问题
> [hotfix_871][taier-worker-plugin] script-core build Dir is error

- taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTaskService.java
- taier-data-develop/src/main/java/com/dtstack/taier/develop/service/template/ftp/FTPColumn.java
- taier-data-develop/src/main/java/com/dtstack/taier/develop/service/template/ftp/FTPWriteParam.java
- API response result changes of the `/taier/api/task/parsing_ftp_columns`
```
{
"code": 1,
"message": null,
"data": {
"column": [
{
"index": 2,
"type": "string",
-- "name": "column2"
++ "key": "column2"
}
],
"filetype": "TXT"
},
"space": 0,
"success": true,
"version": null
}
```
- Add writer's field index autofill
> fixed: ftp target index #938 no initial value given

- pom.xml
升级fastjson版本到1.2.83,1.2.83版本之前存在代码执行漏洞风险，CVE-2022-25845
> 升级fastjson版本到1.2.83,1.2.83版本之前存在代码执行漏洞风险，CVE-2022-25845

- taier-ui/src/pages/operation/schedule.scss
- taier-ui/src/pages/operation/schedule.tsx
修复周期任务列表左下角的按钮折行
fix [#1117](https://github.com/DTStack/Taier/issues/1117)
> fix: dropdown button wrap

- taier-ui/package.json
- 限制 Node 的版本小于 18
Closed #1119
> [build/engines][taier-ui]: restrict node's version lower than 18

- taier-ui/package.json
dt-sql-parser发布了最新版本，generic更名为mysql，导致文件找不到，故限制dt-sql-parser版本
fix https://github.com/DTStack/Taier/issues/1144
> [issue_1144][tail-ui] restrict dt-sql-parser's version

- taier-datasource/taier-datasource-api/src/main/java/com/dtstack/taier/datasource/api/constant/ConfigConstants.java
解决datasource plugin里的ProxyThreadPoolManager在设置线程池时无法拿到正确的参数。
改之前：
在application.properties里配的是
taier.datasource.execute.pool.max.size=30
改之后
在application.properties里配的是
taier.datasource.executePoolMaxSize=30
> [feat_datasource_config][Taier-datasource] fix datasource config bug

- docker-compose.yml
Use docker-compose syntax to explicitly specify the name of the container after it is started to avoid container name format errors when docker-compose is repeatedly executed.
check it #1160
> [issue_1160][docker] Fixed name error when using docker-compose
